# Generated by Django 5.0.6 on 2024-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('descricao', models.TextField()),
                ('castrado', models.BooleanField()),
                ('vacinado', models.BooleanField()),
                ('vermifugado', models.BooleanField()),
                ('sexo', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], max_length=1)),
                ('tipo', models.CharField(choices=[('Gato', 'Gato'), ('Cachorro', 'Cachorro')], max_length=10)),
            ],
        ),
    ]
