# Generated by Django 5.0.6 on 2024-06-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_animais_url_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='porte',
            field=models.CharField(choices=[('Pequeno Porte', 'Pequeno Porte'), ('Médio Porte', 'Médio Porte'), ('Grande Porte', 'Grande Porte')], default='Médio Porte', max_length=20),
        ),
        migrations.AlterField(
            model_name='animais',
            name='url_imagem',
            field=models.CharField(default='https://static.wixstatic.com/media/f94f12_6af5c43bf13048b9b0d22534c7ed9cd7~mv2.png/v1/fill/w_240,h_160,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/logo%20vetorizado.png', max_length=100),
        ),
    ]
