# Generated by Django 5.0.6 on 2024-06-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_animais_porte_alter_animais_url_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='url_imagem',
            field=models.CharField(default='https://static.wixstatic.com/media/f94f12_6af5c43bf13048b9b0d22534c7ed9cd7~mv2.png', max_length=100),
        ),
    ]
