# Generated by Django 5.0.6 on 2024-06-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_animais_url_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='idade',
            field=models.CharField(choices=[('Filhote', 'Filhote'), ('Adulto', 'Adulto'), ('Idoso', 'Idoso')], max_length=10),
        ),
    ]
