# Generated by Django 5.0.6 on 2024-06-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_animais_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='felv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animais',
            name='fiv',
            field=models.BooleanField(default=False),
        ),
    ]
